CI: Cache homebrew deps

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -85,18 +85,26 @@ jobs:
       CPPFLAGS: '-I/opt/homebrew/opt/llvm/include'
     steps:
     - uses: actions/checkout@v4
+    - name: Cache Homebrew
+      uses: actions/cache@v3
+      with:
+        path: |
+          /usr/local/Homebrew/Library/Taps  # Homebrew Taps (Intel Macs)
+          /usr/local/Cellar                # Installed dependencies (Intel Macs)
+          /opt/homebrew/Cellar             # Installed dependencies (Apple Silicon Macs)
+        key: brew-cache-${{ runner.os }}-${{ hashFiles('.github/workflows/Brewfile') }}
+        restore-keys: |
+          brew-cache-${{ runner.os }}-
+
     - name: Install dependencies
       run: |
         curl -fsSL https://bun.sh/install | bash
         PATH=$HOME/.bun/bin:$PATH
         brew update
-        brew install \
-          llvm@19 \
-          freeglut \
-          libpng \
-          meson \
-          ninja
-        brew install --cask xquartz
+        brew bundle --file=.github/workflows/Brewfile || {
+          echo "Some dependencies failed to install, running brew doctor..."
+          brew doctor
+        }
         cd /opt/homebrew/opt/llvm/bin
         #ln -s clang++ clang++-19
         PATH=/opt/homebrew/opt/llvm/bin:$PATH
